name: Gettext

on:
  # This workflow does't run every push because it takes some time to build
  # the app and not always translatable strings are modified on every push
  schedule:
    - cron: "0 9 15 * *"
  workflow_dispatch: {}

jobs:
  gettext:
    name: Gettext
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/elementary/flatpak-platform/runtime:8.1
      options: --privileged

    steps:
    - name: Install git, python3-git and jq
      run: |
        apt-get update
        apt-get install git jq python3-git -y

    - name: Clone repository
      uses: actions/checkout@v6
      with:
        token: ${{ secrets.GIT_USER_TOKEN }}

    - name: Configure Git
      run: |
        git config --global --add safe.directory "$GITHUB_WORKSPACE"

    - name: Update Translation Files
      uses: elementary/actions/gettext-flatpak@main
      with:
        manifest-path: com.github.ryonakano.reco.yml
      env:
        GIT_USER_NAME: "github-actions[bot]"
        GIT_USER_EMAIL: "41898282+github-actions[bot]@users.noreply.github.com"
